name: Android Build

on:
  push:
    branches:
      - 'actions/*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.checkout.outputs.result }}

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and assemble release
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease

    - name: Upload APKs
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: |
          app/build/outputs/apk/release/*.apk
